name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: polar-sierra-90205
          heroku_email: olivierlutz8@gmail.com
      - uses: michcio1234/heroku-run@0.1.1
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: olivierlutz8@gmail.com
          heroku_app_name: polar-sierra-90205
          command: rake db:migrate
